services:
  listening.main.webapi:
    image: listening.main.webapi:local
    build:
      context: .
      dockerfile: Listening.Main.WebAPI/Dockerfile
    ports:
      - "50404:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultDB__ConnStr=Server=host.docker.internal,1433;Database=YouCJVNextDB;User Id=sa;Password=YourStrongPassword!123;TrustServerCertificate=True
    networks:
      - shared
    restart: unless-stopped

  listening.admin.webapi:
    image: listening.admin.webapi:local
    build:
      context: .
      dockerfile: Listening.Admin.WebAPI/Dockerfile
    ports:
      - "50403:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultDB__ConnStr=Server=host.docker.internal,1433;Database=YouCJVNextDB;User Id=sa;Password=YourStrongPassword!123;TrustServerCertificate=True
    networks:
      - shared
    restart: unless-stopped

  file.service.webapi:
    image: file.service.webapi:local
    build:
      context: .
      dockerfile: FileService.WebAPI/Dockerfile
    ports:
      - "50401:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultDB__ConnStr=Server=host.docker.internal,1433;Database=YouCJVNextDB;User Id=sa;Password=YourStrongPassword!123;TrustServerCertificate=True
    volumes: 	                  
      - G:/work/project/net/NETBookMaterials-main/最后大项目代码/YouZack-VNext/FileService.WebAPI/wwwroot:/app/wwwroot
        
    networks:
      - shared
    restart: unless-stopped

  mediaencoder.webapi:
    image: mediaencoder.webapi:local
    build:
      context: .
      dockerfile: MediaEncoder.WebAPI/Dockerfile
    ports:
      - "50405:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultDB__ConnStr=Server=host.docker.internal,1433;Database=YouCJVNextDB;User Id=sa;Password=YourStrongPassword!123;TrustServerCertificate=True
    networks:
      - shared
    restart: unless-stopped

  searchservice.webapi:
    image: searchservice.webapi:local
    build:
      context: .
      dockerfile: SearchService.WebAPI/Dockerfile
    ports:
      - "50406:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultDB__ConnStr=Server=host.docker.internal,1433;Database=YouCJVNextDB;User Id=sa;Password=YourStrongPassword!123;TrustServerCertificate=True
    networks:
      - shared
    restart: unless-stopped

  identityservice.webapi:
    image: identityservice.webapi:local
    build:
      context: .
      dockerfile: IdentityService.WebAPI/Dockerfile
    ports:
      - "50402:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DefaultDB__ConnStr=Server=host.docker.internal,1433;Database=YouCJVNextDB;User Id=sa;Password=YourStrongPassword!123;TrustServerCertificate=True
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    external: true
    name: my-shared-net
